<a href="https://colab.research.google.com/github/rally-adty/UNSIA-Data-Sciense-SM-4/blob/main/Pertemuan6_M_Rally_Adityo_240401010212.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import (
    LabelEncoder,
    MinMaxScaler,
    StandardScaler,
    RobustScaler
)

In [3]:
from google.colab import files

uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [4]:
df = pd.read_csv('titanic.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df['Embarked'] = df['Embarked'].fillna(
    df['Embarked'].mode()[0]
)

df = pd.get_dummies(
    df,
    columns=['Embarked'],
    drop_first=True,
    dtype=int
)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,0,1
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,0,1

In [9]:
df['Age'] = df['Age'].fillna(
    df['Age'].median()
)

In [10]:
df = df.drop(
    columns=[
        'PassengerId',
        'Name',
        'Ticket',
        'Cabin'
    ]
)

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    1  22.0      1      0   7.2500           0           1
1         1       1    0  38.0      1      0  71.2833           0           0
2         1       3    0  26.0      0      0   7.9250           0           1
3         1       1    0  35.0      1      0  53.1000           0           1
4         0       3    1  35.0      0      0   8.0500           0           1

In [11]:
X = df.drop(
    'Survived',
    axis=1
)

y = df['Survived']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [13]:
minmax = MinMaxScaler()

X_train_mm = minmax.fit_transform(
    X_train
)

X_test_mm = minmax.transform(
    X_test
)

print(X_train_mm[:5])

[[1.         1.         0.34656949 0.         0.         0.11027246
  0.         1.        ]
 [0.5        1.         0.34656949 0.         0.         0.
  0.         1.        ]
 [0.         1.         0.34656949 0.         0.         0.43288417
  0.         1.        ]
 [1.         0.         0.22090978 0.         0.16666667 0.01824998
  0.         1.        ]
 [0.5        0.         0.3842674  0.125      0.16666667 0.05123659
  0.         1.        ]]

In [14]:
standard = StandardScaler()

X_train_std = standard.fit_transform(
    X_train
)

X_test_std = standard.transform(
    X_test
)

print(X_train_std[:5])

[[ 0.82956755  0.74242727 -0.11207776 -0.46508428 -0.46618317  0.5138115
  -0.28933346  0.61197825]
 [-0.37094484  0.74242727 -0.11207776 -0.46508428 -0.46618317 -0.66256323
  -0.28933346  0.61197825]
 [-1.57145722  0.74242727 -0.11207776 -0.46508428 -0.46618317  3.95539858
  -0.28933346  0.61197825]
 [ 0.82956755 -1.34693328 -0.87980748 -0.46508428  0.72778236 -0.46787435
  -0.28933346  0.61197825]
 [-0.37094484 -1.34693328  0.11824116  0.47833454  0.72778236 -0.11597681
  -0.28933346  0.61197825]]

In [15]:
robust = RobustScaler()

X_train_rb = robust.fit_transform(
    X_train
)

X_test_rb = robust.transform(
    X_test
)

print(X_train_rb[:5])

[[ 0.          0.          0.          0.          0.          1.81965184
   0.          0.        ]
 [-1.          0.          0.          0.          0.         -0.6256092
   0.          0.        ]
 [-2.          0.          0.          0.          0.          8.97347668
   0.          0.        ]
 [ 0.         -1.         -0.71428571  0.          1.         -0.22092087
   0.          0.        ]
 [-1.         -1.          0.21428571  1.          1.          0.51054787
   0.          0.        ]]

In [16]:
print("X Train :", X_train.shape)
print("X Test  :", X_test.shape)

print("Y Train :", y_train.shape)
print("Y Test  :", y_test.shape)

X Train : (712, 8)
X Test  : (179, 8)
Y Train : (712,)
Y Test  : (179,)

In [17]:
print("Train")
print(y_train.value_counts(normalize=True))

print("\nTest")
print(y_test.value_counts(normalize=True))

Train
Survived
0    0.616573
1    0.383427
Name: proportion, dtype: float64

Test
Survived
0    0.614525
1    0.385475
Name: proportion, dtype: float64