<a href="https://colab.research.google.com/github/rally-adty/UNSIA-Data-Sciense-SM-4/blob/main/Pertemuan10_M_Rally_Adityo_240401010212.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pertemuan 10

**Nama Lengkap :** Maulana Rally Adityo

**NIM :** (240401010212)  

**Kelas :** (IF401)

Program Studi Informatika

In [1]:
import pandas as pd

Mengimpor library Pandas untuk mengolah data.

In [3]:
import numpy as np

Mengimpor library NumPy untuk perhitungan numerik.

In [4]:
import matplotlib.pyplot as plt

Mengimpor library Matplotlib untuk membuat grafik.

In [5]:
from sklearn.model_selection import train_test_split

Mengimpor fungsi untuk membagi data menjadi training dan testing.

In [6]:
from sklearn.ensemble import RandomForestClassifier

Mengimpor algoritma Random Forest.

In [7]:
from sklearn.metrics import accuracy_score

Mengimpor fungsi untuk menghitung akurasi model.

In [8]:
from google.colab import files

Mengimpor fitur upload file pada Google Colab.

In [13]:
uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv

Menampilkan tombol untuk mengunggah file.

In [14]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

Membaca file CSV ke dalam DataFrame.

In [15]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Menampilkan 5 data pertama.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

Menampilkan informasi setiap kolom.

In [17]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

Menampilkan ringkasan statistik data.

In [18]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Menghitung jumlah data kosong.

In [19]:
X = df.drop("Churn", axis=1)

Memisahkan kolom fitur.

In [20]:
y = df["Churn"]

Menentukan kolom target.

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

Membagi data menjadi training (80%) dan testing (20%).

In [22]:
rf = RandomForestClassifier(
    n_estimators=300,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42
)

Membuat model Random Forest.

In [25]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [26]:
df.select_dtypes(include="object").columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges',
       'Churn'],
      dtype='object')

In [27]:
df.drop("customerID", axis=1, inplace=True)

In [28]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [29]:
df.dropna(inplace=True)

In [30]:
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

In [31]:
df = pd.get_dummies(df, drop_first=True)

In [32]:
df.select_dtypes(include="object").columns

Index([], dtype='object')

In [33]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [35]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300,
                       random_state=42)

Melatih model menggunakan data training.

In [36]:
y_pred = rf.predict(X_test)

Melakukan prediksi pada data testing.

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

Menghitung nilai akurasi model.

In [50]:
print(accuracy)

0.7874911158493249

Menampilkan hasil akurasi.

## Kesimpulan

Pada praktikum ini telah berhasil dibangun model klasifikasi menggunakan algoritma **Random Forest** untuk memprediksi pelanggan yang berpotensi melakukan **Customer Churn**. Dataset berhasil diproses melalui tahap preprocessing, seperti menghapus kolom yang tidak diperlukan, mengubah data kategorikal menjadi numerik, serta membagi data menjadi data latih dan data uji.

Berdasarkan hasil evaluasi menggunakan **Accuracy**, **Classification Report**, dan **Confusion Matrix**, model mampu melakukan prediksi dengan baik terhadap data pelanggan. Random Forest terbukti efektif karena mampu menangani data dengan banyak fitur serta menghasilkan performa yang baik dalam proses klasifikasi.

Secara keseluruhan, algoritma **Random Forest** merupakan salah satu metode yang tepat untuk menyelesaikan permasalahan klasifikasi seperti prediksi **Customer Churn**, karena memiliki tingkat akurasi yang baik dan mampu mengurangi risiko overfitting dibandingkan Decision Tree tunggal.